monsite/monsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("sondage/", include("sondage.urls")),
    path('admin/', admin.site.urls),
]

monsite/sondage/urls.py
from django.urls import path

from . import views
app_name = "sondage"
urlpatterns = [
    # path('', views.index, name="index"),
    
    # path("", views.index, name="index"),
    # path("<int:question_id>/", views.detail, name="detail"),
    # path("<int:question_id>/results/", views.results, name="results"),
    # path("<int:question_id>/vote/", views.vote, name="vote"),

    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),

    path("login/",views.my_login,name="login"),
    path("register/",views.register,name="register"),
    path("registered/", views.registered, name="registered"),
    path("welcome/", views.welcome,name="welcome"),
    path("profil/", views.profil,name="profil"),
    path("profil/become/", views.become,name="become"),



]

monsite/sondage/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date de publication")

    def __str__(self):
        return self.question_text

    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def was_published_recently(self):
        now=timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Citizen(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    electeur = models.BooleanField(default=False)

monsite/sondage/views.py
# from multiprocessing import context
# from re import template
# from unittest import loader
# from urllib import response
from multiprocessing import AuthenticationError, context
from django.shortcuts import render, get_object_or_404

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from .models import Citizen, Question, Choice
# from django.template import loader
from django.urls import reverse

from django.views import generic

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from django.utils import timezone

def index(request):
    # # # return HttpResponse("Bienvenue a l'index de notre sondage")

    # # latest_question_list = Question.objects.order_by("-pub_date")[:5]
    # # output = "<br>" .join([q.question_text for q in latest_question_list])
    # # return HttpResponse(output)

    # latest_question_list = Question.objects.order_by("-pub_date")[:5]
    # template = loader.get_template("sondage/index.html")
    # context = {"question_list": latest_question_list}
    # return HttpResponse(template.render(context, request))

    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"question_list": latest_question_list}
    return render(request, "sondage/index.html", context)


def detail(request, question_id):
    # # return HttpResponse("Voici la question numéro %s." % question_id)

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("La question n'existe pas")
    # return render(request, "sondage/detail.html", {"question":question})

    question = get_object_or_404(Question, pk=question_id)
    return render(request, "sondage/detail.html",{"question":question})

    

def results(request, question_id):
    # response = "Voici les votes de la question numéro %s."
    # return HttpResponse(response % question_id)

    question = get_object_or_404(Question, pk=question_id)
    return render(request, "sondage/results.html", {"question":question})

def vote(request, question_id):
    # return HttpResponse("vous votez pour la question %s." % question_id)

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request,"sondage/detail.html",{"question":question,"error_message":"Vous devez choisir !!",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("sondage:results", args=(question_id,)))

class IndexView(generic.ListView):
    template_name = "sondage/index.html"
    context_object_name = "question_list"

    def get_queryset(self):
        # return Question.objects.order_by("-pub_date")[:5]
        return Question.objects.filter(pub_date__lte = timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "sondage/detail.html"

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "sondage/results.html"

def my_login(request):
    return render(request,"sondage/login.html")

def register(request):
    return render(request,"sondage/register.html")

def my_logout(request):
        return render(request,"sondage/logout.html")

def registered(request):
    name = request.POST["user_name"]
    firstname = request.POST["user_firstname"]
    pwd = request.POST["user_pwd"]
    email = request.POST["user_email"]
    username= firstname[0].lower() + "." + name.lower()
    user = User.objects.create_user(username, email, pwd)
    citizen = Citizen(user=user)
    user.last_name = name
    user.first_name = firstname
    user.save()
    citizen.save()
    context = {"user": user}
    return render(request,'sondage/registered.html', context)

def welcome(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user= authenticate(request, username=username,password=password)
    context = {"user":user}
    if user is not None:
        login(request,user)
        return render(request,"sondage/welcome.html",context)
    else:
        return render(request, "sondage/error_log.html")
    
def my_logout(request):
    logout(request)
    return render(request,"sondage/logout.html")

def profil(request):
    citizen = Citizen.objects.get(user=request.user)
    context = {"citizen":citizen}
    return render(request,"sondage/profil.html", context)

def become(request):
    request.user.citizen.electeur = True
    request.user.citizen.save()
    return IndexView.as_view()(request)

monsite/sondage/templates/sondage/detail.html
<!DOCTYPE html>
<html lang="fr" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
    <!-- <h1>Question numéro {{question.id}}</h1>
<p>{{question}}</p>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{choice}}</li>
    {% endfor %}
</ul> -->

{% if request.user.is_authenticates %}
{% if request.user.citizen.electeur %}
<form action="{% url 'sondage:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
  <legend><h1>{{ question.question_text }}</h1></legend>
  {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id}}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
  {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
{% else %}
<i>Seul les élécteurs peuvent voter</i>
{% endif %}  
{% else %}
  <a href="{% url 'sondage:login' %}"><i>Vous devez être connecté pour pouvoir voter</i></a>
{% endif %}  
</body>

</html>

monsite/sondage/templates/sondage/error_log.html
<p>Indentifiant ou mot de passe incorrecte</p>
<a href="{% url 'sondage:login' %}">login</a>

monsite/sondage/templates/sondage/index.html
<!DOCTYPE html>
{% load static %}
<html lang="fr" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>mon sondage</title>
<link rel="stylesheet" type="text/css" href="{% static 'sondage/style.css' %}">
</head>

<body>
{% block contenue %}
  {% if not request.user.is_authenticated %}
 <a href="{% url 'sondage:login' %}">connexion</a>
 <a href="{% url 'sondage:register' %}">inscription</a>
 {% else %}
 <a href="{% url 'sondage:logout' %}">déconnexion</a>
 <a href="{% url 'sondage:profil' %}">profil</a>

 {% endif %}
{% endblock %}
  {% if question_list %}
  <ul>
      {% for question in question_list %}
      <li>
          <a href="/sondage/{{question.id}}">{{question.question_text}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Pas de sondage disponible.</p>
    {% endif %}

</body>

</html>

monsite/sondage/templates/sondage/login.html
<form id="login" method="post" action="{% url 'sondage:welcome' %}">
    {% csrf_token %}
    <table class="table table-striped table-sm">
        <tr>
            <td>
                <label for="username">Login</label>
                <input id="username" name="username">
            </td>
            <td>
                <label for="password">Mot de Passe</label>
                <input type="password" id="password" name="password">
            </td>
            <td>
                <input type="submit" name="Connexion">
            </td>
        </tr>
    </table>
</form>

monsite/sondage/templates/sondage/logout.html
<p>A Bientot !</p>

<a href="{% url 'sondage:index'%}">index</a>

monsite/sondage/templates/sondage/profil.html
{% extends 'sondage/index.html'%}
{% load static %}
{% block contenue %}
    <h1>{{request.user.username}}</h1>
    {% if citizen.electeur == false %}
        <a href="{% url 'sondage:become' %}">Devenir electeur</a>
    {%endif%}
{% endblock %}

monsite/sondage/templates/sondage/register.html
<form id="register" method="post" action="{% url 'sondage:registered' %}">
    {% csrf_token %}
    <table class="table table-striped table-sm">
        <tr>
            <td>
                <label for="user_name">NOM</label>
                <input id="user_name" name="user_name">
            </td>
        </td>
        <tr>
            <td>
                <label for="user_firstname">Prénom</label>
                <input id="user_firstname" name="user_firstname">
            </td>
        </tr>
            <tr>
                <td>

                <label for="user_email">Email</label>
                <input id="user_email" name="user_email">
            </td>
            </tr>
           
            <tr>
                <td>
                    <label for="user_pwd">Mot de passe</label>
                    <input type="password" id="user_pwd" name="user_pwd">
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Enregistrer">
                </td>
        </tr>
    </table>
</form>

monsite/sondage/templates/sondage/registered.html
<h1>Bienvenue !</h1>
<p>Votre nom d'utilisateur est {{user.ussername}}</p>
<a href="{% url 'sondage:login'%}">Login</a>

monsite/sondage/templates/sondage/results.html
<h1>{{ question.question_text }}</h1>
<ul>
  {% for choice in question.choice_set.all%}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>
<a href="{% url 'sondage:detail' question.id %}">Voter a nouveau ?</a>

monsite/sondage/templates/sondage/welcome.html
<h1>Bienvenue {{user.username}} !</h1>
<p>Connexion réussi</p>
<a href="{% url 'sondage:index'%}">Page d'accueil</a>